# Generated by Django 4.2.16 on 2024-11-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
